DeleteCredentialConfigurationForMosipid:
  InjiCertify_Delete_Mosipid_for_1.1_valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_Delete_Credential_Config_Mosipid_01
    description: Delete Credential configuration for land registry for csr certificate flow
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/VCIMosipID/DeleteCredentialConfigurationForMosipid/DeleteCredentialConfigurationForMosipid
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_MosipID_all_Valid_Smoke_sid_id$"
      }'
    output: '{
	"responseCode": "200"    
    }'