/*
 * Copyright 2024 Modular Open Source Identity Platform
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.mosip.certify.proof;

import java.util.Map;

public interface ProofValidator {

    /**
     * Proof type supported by the implementation class.
     * @return Returns the supported proof type
     */
    String getProofType();

    /**
     * Validates the input proof.
     * @param clientId Client ID as in the bearer access token
     * @param cNonce valid client nonce as generated by the server(authorization/VCI)
     * @param proofJwt from the credential request.
     * @return true if proof passes all the validation else false
     */
    boolean validate(String clientId, String cNonce, String proofJwt, Map<String, Object> proofConfiguration);

    /**
     * Extracts the holders public key for VC cryptographic binding from the proof header
     * @param proofJwt from the credential request.
     * @return public key as did:jwk equivalent
     */
    String getKeyMaterial(String proofJwt);
}