# Copyright 2024 Modular Open Source Identity Platform
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## ------------------------------------------- Plugin enable properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.vci-plugin=MDocMockVCIssuancePlugin
mosip.certify.plugin-mode=VCIssuance

##commons
mosip.certify.status-list.signature-crypto-suite=Ed25519Signature2018

## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
mosip.certify.cache.secure.individual-id=false
mosip.certify.cache.store.individual-id=false
mosip.certify.cache.security.algorithm-name=AES/ECB/PKCS5Padding
#TODO:Onboard issuer key and certificate data here format - "$base64EncodedPrivateKey||$base64EncodedCertificate"
mosip.certify.mock.mdoc.issuer-key-cert=
mosip.certify.mock.vciplugin.mdoc.issuer-key-cert=${mosip.certify.mock.mdoc.issuer-key-cert}

## ------------------------------------------- Host values of connected services ------------------------------------------------------------
mosip.injicertify.mock.host=localhost:8090
mosip.api.public.host=api.collab.mosip.net

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=http://${mosip.injicertify.mock.host}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.database.name=inji_certify_mock
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Transport Department Issuer',\
    'locale': 'en',\
    'logo':{'uri':'https://inji.github.io/inji-config/logos/mosipid-logo.png',\
         'alt_text':'mosip-logo'}\
  }\
}
